import { Neighbourhood } from "./types";

// Coordinates are approximate neighbourhood centroids (hand-placed from general
// knowledge of Toronto geography), not surveyed boundaries — good enough for a
// city-wide comparison map, but refine with a geocoder if you need precision
// for a specific address.
export const NEIGHBOURHOODS: Neighbourhood[] = [
  { id: "annex", name: "The Annex", tier: "$$$", lines: ["line2"], lat: 43.6708, lng: -79.4064, t: 5, w: 5, f: 4, fun: 3, p: 3, d: 3, g: 4, q: 3, s: 4,
    note: "Leafy and studenty, anchored by Bloor St W and U of T's St. George campus — one of the most walkable, transit-rich parts of the city (Spadina and Bathurst stations on Line 2, plus the 510 Spadina streetcar). Bloor's bookstores, bars and late-night eats around the old Honest Ed's block (now Mirvish Village) keep it lively into the evening, which also makes it one of the noisier residential pockets on this list. Small parks like Sibelius Park and Vermont Square give casual dog-walking room, though Christie Pits just south is the nearest real off-leash option. A classic first stop for newcomers who want to be close to everything without a car." },
  { id: "kensington", name: "Kensington Market", tier: "$$", lines: ["streetcar"], lat: 43.6547, lng: -79.4005, t: 2, w: 5, f: 5, fun: 3, p: 2, d: 2, g: 5, q: 2, s: 3,
    note: "Bohemian and intensely walkable — narrow streets (Augusta, Baldwin, Kensington Ave) packed with vintage shops and some of the city's best casual and international food, spilling into neighbouring Chinatown along Spadina for produce and grocery. No subway station sits in the market itself (St. Patrick or Spadina are a 10–15 min walk, plus the 510 Spadina streetcar), and packed sidewalks, buskers and Pedestrian Sundays (May–Oct) make this one of the louder, busier picks here — charming, not a quiet retreat. Green space is limited to small pocket parks like Bellevue Square; Trinity Bellwoods is a 15-minute walk west for dog owners." },
  { id: "westqueenwest", name: "West Queen West", tier: "$$$", lines: ["streetcar"], lat: 43.6448, lng: -79.4230, t: 2, w: 5, f: 5, fun: 4, p: 4, d: 4, g: 3, q: 2, s: 3,
    note: "Toronto's gallery-and-boutique strip, centred on the 501 Queen streetcar with MOCA (Museum of Contemporary Art), the Drake and Gladstone hotels, and a dense run of restaurants and bars that keep Queen St W loud on weekend nights. Its biggest asset for parks and dogs is Trinity Bellwoods — a large, heavily used off-leash area and one of the best green spaces downtown. No subway runs directly through; it's a longer walk to Osgoode or Dufferin stations." },
  { id: "roncesvalles", name: "Roncesvalles", tier: "$$$", lines: ["streetcar", "line2"], lat: 43.6480, lng: -79.4490, t: 3, w: 4, f: 4, fun: 2, p: 4, d: 4, g: 4, q: 3, s: 4,
    note: "A café-and-bakery-lined main street with a strong Polish heritage (a street festival most Septembers), sitting between High Park and Sunnyside Beach on the waterfront — some of the best park and trail access on this list. The 504 King streetcar runs its length and Dundas West station (Line 2) anchors the north end, so transit is solid without being downtown-fast. Quieter and more residential than King West or Queen West, with High Park's trails right next door for dog walks." },
  { id: "highpark", name: "High Park North", tier: "$$", lines: ["line2"], lat: 43.6537, lng: -79.4635, t: 4, w: 3, f: 3, fun: 2, p: 5, d: 5, g: 3, q: 4, s: 5,
    note: "Defined by High Park itself — 400+ acres with trails, Grenadier Pond, the free High Park Zoo and a well-used off-leash dog area, making this the top pick here for parks and dog-friendliness. Line 2 (Keele and High Park stations) gives a fairly direct ~20-minute subway ride downtown, though the immediate area is quieter and more residential than commercial — day-to-day walkability to shops and restaurants is more limited than in the Junction or Roncesvalles nearby." },
  { id: "junction", name: "The Junction", tier: "$$", lines: ["line2"], lat: 43.6650, lng: -79.4630, t: 3, w: 4, f: 4, fun: 3, p: 2, d: 2, g: 4, q: 3, s: 4,
    note: "A former rail-and-stockyards district turned craft-beer strip — Dundas St W here holds several breweries (Indie Alehouse, Junction Craft Brewing), antique shops and a Saturday farmers' market. Line 2 (Keele or Runnymede, roughly a 10-minute walk from the main strip) covers subway access, though the neighbourhood has fewer parks than its western neighbours and no off-leash dog area of its own." },
  { id: "kingwest", name: "King West", tier: "$$$$", lines: ["streetcar"], lat: 43.6440, lng: -79.4000, t: 3, w: 5, f: 5, fun: 5, p: 2, d: 2, g: 3, q: 1, s: 3,
    note: "Condo-tower dense and built around nightlife — the King St W restaurant and club strip (spilling into the neighbouring Entertainment District) makes this the loudest neighbourhood on this list late at night, and a one-bedroom here often runs $2,300+. The 504 King streetcar is the transit backbone since no subway runs directly through; walk to St. Andrew or Osgoode (Line 1) for that. Green space is scarce — Clarence Square and Victoria Memorial Square are the nearest options — so this suits people who want nightlife and walkability over parks or quiet." },
  { id: "financial", name: "Financial District", tier: "$$$$", lines: ["line1", "line2"], lat: 43.6488, lng: -79.3817, t: 5, w: 4, f: 3, fun: 2, p: 1, d: 1, g: 2, q: 2, s: 4,
    note: "Office towers by day, connected by the underground PATH network and Union Station (Line 1, Line 2 via the St. George/Yonge interchange, plus every GO train line) — the best raw transit access in the city. Comparatively few people actually live here full-time, so evening street life, grocery options and casual dining thin out fast once offices empty, and there's almost no park or dog space in the immediate core." },
  { id: "entertainment", name: "Fashion / Entertainment District", tier: "$$$", lines: ["streetcar", "line1"], lat: 43.6435, lng: -79.3910, t: 4, w: 5, f: 4, fun: 5, p: 1, d: 1, g: 2, q: 1, s: 3,
    note: "Home to the Rogers Centre, Scotiabank Arena and CN Tower — Toronto's event district. Expect noise and crowds on game or concert nights, and a lively but fairly touristy restaurant scene. St. Andrew and Osgoode (Line 1) plus the King and Queen streetcars give strong transit access; parks are limited to small squares like Clarence Square, with very little dog-friendly green space." },
  { id: "cityplace", name: "CityPlace / Queens Quay", tier: "$$$", lines: ["streetcar", "go"], lat: 43.6400, lng: -79.3900, t: 2, w: 3, f: 3, fun: 3, p: 3, d: 2, g: 3, q: 2, s: 4,
    note: "A cluster of newer lakefront condo towers along Lake Shore Blvd and Fort York Blvd, with Canoe Landing Park, the Toronto Music Garden and Harbourfront's trails and ferry terminals nearby for waterfront walking and limited green space. It's a walk to Union Station for the subway proper, though the 509/510 streetcars run through and GO trains are close by; a Loblaws at Canoe Landing covers grocery basics on-site." },
  { id: "yorkville", name: "Yorkville", tier: "$$$$", lines: ["line1"], lat: 43.6709, lng: -79.3933, t: 5, w: 5, f: 4, fun: 3, p: 2, d: 2, g: 3, q: 3, s: 5,
    note: "Toronto's high-end shopping and dining district (Bloor-Yorkville, Yorkville Village), a short walk from the ROM, with Bay and Museum stations (Line 1) giving fast, direct subway access. Ramsden Park and Cumberland Park add modest green space, though it's not a big-park neighbourhood; among the priciest addresses in the city, and generally calm and well-kept in the evenings." },
  { id: "cabbagetown", name: "Cabbagetown", tier: "$$$", lines: ["streetcar", "bus"], lat: 43.6675, lng: -79.3660, t: 2, w: 4, f: 3, fun: 2, p: 3, d: 3, g: 3, q: 4, s: 4,
    note: "Toronto's largest continuous stretch of Victorian rowhouses, centred on Parliament St, with Riverdale Farm and Allan Gardens' conservatory as neighbourhood-defining green spaces. No subway station sits within the neighbourhood itself — the 506 Carlton streetcar and buses to Castle Frank or Sherbourne (Line 2) cover transit — which keeps the residential streets notably quieter than downtown proper." },
  { id: "yongeeglinton", name: "Yonge & Eglinton", tier: "$$$", lines: ["line1", "line5"], lat: 43.7050, lng: -79.3985, t: 5, w: 4, f: 4, fun: 3, p: 2, d: 2, g: 4, q: 2, s: 4,
    note: "A major retail and office node ('Yonge & Eg') at the crossing of Line 1 and Line 5, the Eglinton Crosstown LRT that opened in February 2026 between Mount Dennis and Kennedy — a real improvement for crosstown trips if your commute runs east-west rather than straight downtown. Busy and commercial right at the intersection, with Eglinton Park a few minutes' walk for green space; popular with young professionals for the transit-plus-retail combination." },
  { id: "davisville", name: "Davisville / St. Clair", tier: "$$$", lines: ["line1"], lat: 43.6975, lng: -79.3945, t: 5, w: 4, f: 3, fun: 2, p: 3, d: 3, g: 4, q: 3, s: 4,
    note: "A relaxed stretch along Yonge St between Rosedale and Yonge & Eglinton, well served by Line 1 (Davisville and St. Clair stations) and anchored by June Rowlands Park (Davisville Park) for green space and casual dog-walking. Good grocery access (Whole Foods on St. Clair, plus the usual Yonge St options); generally quieter and more family-oriented than the retail strip just north." },
  { id: "rosedale", name: "Rosedale / Summerhill", tier: "$$$$", lines: ["line1"], lat: 43.6820, lng: -79.3860, t: 4, w: 3, f: 2, fun: 1, p: 4, d: 4, g: 3, q: 5, s: 5,
    note: "Among the most affluent, historic residential streets in the city, laced with ravine parks (the Rosedale Ravine trails, Chorley Park) that make it one of the quietest, most tree-covered neighbourhoods on this list. Rosedale and Summerhill stations (Line 1) provide subway access, but there's very little retail, nightlife or restaurant density within the neighbourhood itself — residents typically go elsewhere for that." },
  { id: "lawrencepark", name: "Lawrence Park / Bedford Park", tier: "$$$$", lines: ["bus", "line1"], lat: 43.7280, lng: -79.4030, t: 2, w: 2, f: 2, fun: 1, p: 4, d: 4, g: 3, q: 5, s: 5,
    note: "A quiet, leafy, family-oriented pocket with wide lots and mature trees, served more by buses than direct subway (the nearest Line 1 stations are a bus ride away). Green space is a strength — Blythwood Ravine Park and John Wanless Park both offer dog-friendly walking trails — but day-to-day walkability to shops and restaurants is lower than almost anywhere else on this list, so expect to rely on a car or transit for errands and nightlife alike." },
  { id: "danforth", name: "Danforth / Greektown", tier: "$$$", lines: ["line2"], lat: 43.6795, lng: -79.3520, t: 5, w: 4, f: 5, fun: 3, p: 3, d: 3, g: 4, q: 3, s: 4,
    note: "Greektown along the Danforth is one of the city's best-regarded strips for restaurants (Greek, and increasingly diverse), and is often cited as safer and more family-friendly than nightlife-heavy areas downtown — it hosts the Taste of the Danforth festival most summers. Multiple Line 2 stations (Chester, Broadview, Pape, Donlands, Greenwood) run its length, giving strong, direct transit. Withrow Park, just north of the main strip, has a well-used off-leash dog area." },
  { id: "leslieville", name: "Leslieville", tier: "$$$", lines: ["streetcar"], lat: 43.6630, lng: -79.3350, t: 2, w: 4, f: 5, fun: 3, p: 3, d: 4, g: 4, q: 3, s: 4,
    note: "A foodie, creative-industry neighbourhood along Queen St E — cafes, brunch spots and indie shops — with Jimmie Simpson Park's off-leash dog area a short walk from most addresses. No subway runs through here directly, so the 501/502/503 streetcars are the transit backbone, but it's flat and walkable, and generally considered family-friendly and low-key compared to the nightlife strips further west." },
  { id: "riverdale", name: "Riverdale", tier: "$$$", lines: ["streetcar"], lat: 43.6685, lng: -79.3520, t: 2, w: 3, f: 3, fun: 2, p: 5, d: 5, g: 3, q: 4, s: 4,
    note: "Victorian homes on quiet residential streets, book-ended by Riverdale Park East and West, which together offer skyline views over the Don Valley, sports fields, and easy access to Riverdale Farm and the off-leash area at neighbouring Withrow Park. The 504/505 streetcars serve the area; no subway runs directly through, so transit is a touch slower than Danforth just north." },
  { id: "beaches", name: "The Beaches", tier: "$$$", lines: ["streetcar"], lat: 43.6710, lng: -79.2980, t: 2, w: 3, f: 3, fun: 2, p: 5, d: 5, g: 3, q: 4, s: 5,
    note: "Toronto's boardwalk neighbourhood — the lakefront walk runs past Kew Gardens Park and Ashbridges Bay, and Woodbine Beach has a dedicated off-leash dog beach, making this one of the strongest picks here for parks and dog access. The tradeoff is commute time: the 501 Queen streetcar is the only direct transit option and the ride downtown is long, so weigh that against lakefront living. Family-oriented and generally calm outside festival weekends like the Beaches International Jazz Festival." },
  { id: "littleindia", name: "Little India (Gerrard)", tier: "$$", lines: ["streetcar"], lat: 43.6720, lng: -79.3260, t: 2, w: 4, f: 5, fun: 2, p: 2, d: 2, g: 4, q: 3, s: 3,
    note: "The Gerrard India Bazaar gives this stretch a genuinely distinct food and shopping scene — South Asian restaurants, sari shops and grocers along Gerrard St E, generally affordable for how central it is. The 506 Gerrard streetcar is the main transit line; parks and dog space are limited compared to neighbourhoods further east or west, so this is more of a walkable, food-first pick than a green-space one." },
  { id: "eastyork", name: "East York", tier: "$$", lines: ["bus"], lat: 43.6910, lng: -79.3280, t: 2, w: 2, f: 2, fun: 1, p: 3, d: 3, g: 3, q: 4, s: 4,
    note: "A quieter, more affordable residential area with fewer restaurants and nightlife options than downtown neighbourhoods, but decent green space via Stan Wadlow Park and the Taylor Creek ravine trail system. Transit here is bus-only — no subway or streetcar runs through East York directly — so commute times depend heavily on which bus route connects to the nearest subway station." },
  { id: "northyork", name: "North York (Yonge corridor)", tier: "$$$", lines: ["line1"], lat: 43.7615, lng: -79.4110, t: 5, w: 3, f: 3, fun: 2, p: 2, d: 2, g: 4, q: 3, s: 4,
    note: "A corridor of residential high-rises strung along the Yonge St subway line, anchored by Mel Lastman Square and the North York Central Library, with several Line 1 stations (North York Centre, Sheppard-Yonge, Finch) giving fast, direct downtown access despite being well north of the core. Grocery options are plentiful along Yonge; Earl Bales Park is the main nearby green space, though the immediate strip is more commercial tower than park." },
  { id: "etobicoke", name: "Etobicoke (subway corridor)", tier: "$$", lines: ["line2"], lat: 43.6435, lng: -79.5320, t: 4, w: 2, f: 2, fun: 1, p: 3, d: 3, g: 3, q: 4, s: 4,
    note: "A more suburban, car-friendly stretch that's still on the subway — Line 2's western stations (Islington, Kipling) anchor the area, and it's close to Pearson Airport if you fly often. Humber River trails and Centennial Park offer green space; day-to-day walkability to restaurants and shops is lower than downtown neighbourhoods, so this suits people prioritizing space and subway access over walkable nightlife." },
  { id: "scarborough", name: "Scarborough", tier: "$", lines: ["line2", "bus"], lat: 43.7764, lng: -79.2318, t: 2, w: 2, f: 3, fun: 1, p: 3, d: 3, g: 3, q: 4, s: 3,
    note: "The most affordable large area on this list, and home to the Scarborough Bluffs — dramatic lakeside cliffs and one of the city's signature parks — plus Rouge National Urban Park, Canada's first national urban park, on its eastern edge. Transit has been in flux: the old Scarborough RT (Line 3) closed in 2023 and ran as an on-street shuttle bus since, but the new Scarborough Busway (reusing part of the old rail corridor) is completing in September 2026 and should speed that connection up considerably; the actual subway extension to Scarborough Town Centre remains under construction with no confirmed opening date, so check current TTC service alerts rather than an old map." },
  { id: "mosspark", name: "Moss Park", tier: "$", lines: ["streetcar"], lat: 43.6580, lng: -79.3690, t: 3, w: 4, f: 2, fun: 2, p: 2, d: 2, g: 2, q: 2, s: 2,
    note: "A downtown-adjacent, transitional neighbourhood officially designated a Neighbourhood Improvement Area by the city, bordered by St. James Town and the Moss Park community centre/park itself. The 504 King and 505 Dundas streetcars keep it well-connected to downtown and walkable to the core, but it scores lower here on safety, quiet and grocery access than most other neighbourhoods on this list.",
    caution: "Worth an in-person daytime and evening visit before deciding — not a reason on its own to rule it out." },
];

export const HOOD_BY_ID: Record<string, Neighbourhood> = Object.fromEntries(
  NEIGHBOURHOODS.map((h) => [h.id, h])
);

export const LINES: Record<string, { label: string; color: string }> = {
  line1: { label: "Line 1", color: "#F8C300" },
  line2: { label: "Line 2", color: "#00A650" },
  line5: { label: "Line 5 Crosstown", color: "#9B59B6" },
  streetcar: { label: "Streetcar", color: "#6C7F8B" },
  go: { label: "GO Train", color: "#1B4B66" },
  bus: { label: "Bus only", color: "#93998F" },
};
